# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('zip_code', models.PositiveSmallIntegerField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('link', models.URLField()),
                ('icon', models.URLField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea.Brand')),
                ('ingredients', models.ManyToManyField(to='tea.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='TeaType',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('steeping_temperature', models.PositiveSmallIntegerField()),
                ('caffeine_level', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('directions', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='tea',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea.TeaType'),
        ),
        migrations.AddField(
            model_name='rating',
            name='tea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea.Tea'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='picture',
            name='tea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea.Tea'),
        ),
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
