# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0002_auto_20180328_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tea',
            old_name='icon',
            new_name='main_picture',
        ),
    ]
